# Generated by Django 3.2.7 on 2022-06-06 12:54

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image_collection', models.ImageField(default='nno', upload_to='products')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('color', colorfield.fields.ColorField(choices=[('#BED5D2', '#BED5D2'), ('#D6EEC4', '#D6EEC4'), ('#002B73', '#002B73'), ('#AC8549', '#AC8549'), ('#BAC0F8', '#BAC0F8'), ('#FDFDFD', '#FDFDFD'), ('#D3D3D2', '#D3D3D2'), ('#FF8888', '#FF8888')], default='#BED5D2', max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('vendor', models.CharField(max_length=150, unique=True)),
                ('price', models.IntegerField()),
                ('price_with_discount', models.IntegerField(blank=True)),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах')),
                ('description', models.TextField()),
                ('size_range', models.CharField(blank=True, default='42-50', max_length=150)),
                ('structure', models.CharField(max_length=150)),
                ('line', models.IntegerField(default=5, verbose_name='Количество в линейке')),
                ('fabric', models.CharField(max_length=150)),
                ('bestseller', models.BooleanField(default=False)),
                ('novelty', models.BooleanField(default=True)),
                ('favorite', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coll', to='product.collection')),
                ('image_color', models.ManyToManyField(related_name='image_color', to='product.ImageProduct')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
