# Generated by Django 3.2.7 on 2022-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.IntegerField(default=1, verbose_name='Количество в линейке'),
        ),
    ]
