# Generated by Django 3.2.7 on 2022-06-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.IntegerField(default=5, verbose_name='Количество в линейке'),
        ),
    ]
