# Generated by Django 3.2.7 on 2022-06-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_line'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomProduct',
        ),
    ]
