# Generated by Django 3.2.7 on 2022-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_randomproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
