# Generated by Django 3.2.7 on 2022-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220603_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='novelty',
            field=models.BooleanField(default=True),
        ),
    ]
