# Generated by Django 3.2.7 on 2022-06-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('line', models.IntegerField(blank=True, null=True, verbose_name='Количество линеек')),
                ('product_quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество товаров')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидки')),
                ('total_cost', models.IntegerField(blank=True, null=True, verbose_name='Итого к оплате')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
