# Generated by Django 3.2.7 on 2022-06-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_about',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aboutUs.about'),
        ),
    ]
