# Generated by Django 3.2.7 on 2022-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('title_advantage', models.CharField(max_length=150)),
                ('description_advantage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image_collection', models.ImageField(default='nno', upload_to='products')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='carusel-img')),
                ('img2', models.ImageField(upload_to='carusel-img')),
                ('img3', models.ImageField(upload_to='carusel-img')),
                ('img4', models.ImageField(upload_to='carusel-img')),
                ('img5', models.ImageField(upload_to='carusel-img')),
                ('main_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_new', models.ImageField(upload_to='products')),
                ('title_new', models.CharField(max_length=50)),
                ('price_new', models.IntegerField()),
                ('price_with_discount_new', models.IntegerField(blank=True)),
                ('discount_new', models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах')),
                ('size_new', models.CharField(max_length=20)),
                ('favorite_new', models.BooleanField(default=False)),
                ('image_color', models.ManyToManyField(related_name='novelty_img_color', to='product.ImageProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('price_with_discount', models.IntegerField(blank=True)),
                ('discount', models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах')),
                ('size', models.CharField(max_length=20)),
                ('favorite', models.BooleanField(default=False)),
                ('image_color', models.ManyToManyField(related_name='bestseller_img_color', to='product.ImageProduct')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
