# Generated by Django 3.2.7 on 2022-06-07 01:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRelation',
            new_name='Favorite',
        ),
    ]
