# Generated by Django 3.2.7 on 2022-06-01 04:25

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bestseller',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageBestseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('color', colorfield.fields.ColorField(choices=[('#bed5d2', 'aquamarine'), ('#d6eec4', 'lightGreen'), ('#002b73', 'tan'), ('#ac8549', 'saddleBrown'), ('#bac0f8', 'lavender'), ('#fdfdfd', 'white'), ('#d3d3d2', 'grey'), ('#ff8888', 'red')], default='#FFFFFF', max_length=18)),
                ('bestseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.bestseller')),
            ],
        ),
    ]
