# Generated by Django 3.2.7 on 2022-06-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
