# Generated by Django 3.2.7 on 2022-05-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='color',
            field=models.CharField(choices=[('2', 'lightGreen'), ('3', 'tan'), ('4', 'saddleBrown'), ('5', 'lavender'), ('6', 'white'), ('7', 'grey'), ('8', 'red')], max_length=20),
        ),
    ]
