# Generated by Django 3.2.7 on 2022-06-07 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220607_0149'),
        ('main', '0002_rename_productrelation_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelty',
            old_name='favorite_new',
            new_name='novelty',
        ),
        migrations.RemoveField(
            model_name='novelty',
            name='discount_new',
        ),
        migrations.RemoveField(
            model_name='novelty',
            name='image_color',
        ),
        migrations.RemoveField(
            model_name='novelty',
            name='image_new',
        ),
        migrations.RemoveField(
            model_name='novelty',
            name='price_new',
        ),
        migrations.RemoveField(
            model_name='novelty',
            name='price_with_discount_new',
        ),
        migrations.RemoveField(
            model_name='novelty',
            name='size_new',
        ),
        migrations.RemoveField(
            model_name='novelty',
            name='title_new',
        ),
        migrations.AddField(
            model_name='novelty',
            name='item1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
