# Generated by Django 3.2.7 on 2022-06-01 04:37

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220601_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebestseller',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
