# Generated by Django 3.2.7 on 2022-06-03 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220602_1148'),
        ('main', '0002_delete_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestseller',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.collection'),
        ),
    ]
