# Generated by Django 3.2.7 on 2022-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bestseller_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='carusel-img')),
                ('img2', models.ImageField(upload_to='carusel-img')),
                ('img3', models.ImageField(upload_to='carusel-img')),
                ('img4', models.ImageField(upload_to='carusel-img')),
                ('img5', models.ImageField(upload_to='carusel-img')),
                ('main_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='color',
            field=models.CharField(choices=[('1', 'aquamarine'), ('2', 'lightGreen'), ('3', 'tan'), ('4', 'saddleBrown'), ('5', 'lavender'), ('6', 'white'), ('7', 'grey'), ('8', 'red')], max_length=20),
        ),
    ]
