# Generated by Django 3.2.7 on 2022-06-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220607_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='img1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='img5',
        ),
    ]
