# Generated by Django 3.2.7 on 2022-05-30 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_novelties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novelties',
            old_name='color',
            new_name='color_new',
        ),
        migrations.RenameField(
            model_name='novelties',
            old_name='discount',
            new_name='discount_new',
        ),
        migrations.RenameField(
            model_name='novelties',
            old_name='favorite',
            new_name='favorite_new',
        ),
        migrations.RenameField(
            model_name='novelties',
            old_name='image',
            new_name='image_new',
        ),
        migrations.RenameField(
            model_name='novelties',
            old_name='price',
            new_name='price_new',
        ),
        migrations.RenameField(
            model_name='novelties',
            old_name='price_without_discount',
            new_name='price_without_discount_new',
        ),
        migrations.RenameField(
            model_name='novelties',
            old_name='size',
            new_name='size_new',
        ),
        migrations.RenameField(
            model_name='novelties',
            old_name='title',
            new_name='title_new',
        ),
    ]
