# Generated by Django 3.2.7 on 2022-06-01 04:51

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_imagebestseller_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebestseller',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#bed5d2', '#bed5d2'), ('#d6eec4', '#d6eec4'), ('#002b73', '#002b73'), ('#ac8549', '#ac8549'), ('#bac0f8', '#bac0f8'), ('#fdfdfd', '#fdfdfd'), ('#d3d3d2', '#d3d3d2'), ('#ff8888', '#ff8888')], default='#FF0000', max_length=18),
        ),
    ]
