# Generated by Django 3.2.7 on 2022-06-01 04:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_imagebestseller_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebestseller',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
