# Generated by Django 3.2.7 on 2022-06-01 04:57

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_imagebestseller_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebestseller',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#BED5D2', '#BED5D2'), ('#D6EEC4', '#D6EEC4'), ('#002B73', '#002B73'), ('#AC8549', '#AC8549'), ('#BAC0F8', '#BAC0F8'), ('#FDFDFD', '#FDFDFD'), ('#D3D3D2', '#D3D3D2'), ('#FF8888', '#FF8888')], default='#FF0000', max_length=18),
        ),
    ]
