# Generated by Django 3.2.7 on 2022-06-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220619_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='cart',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
            preserve_default=False,
        ),
    ]
