# Generated by Django 3.2.7 on 2022-06-15 15:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_status', models.CharField(choices=[('YES', 'ДА'), ('NO', 'НЕТ')], default='NO', max_length=20, verbose_name='Статус позвонили')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('type_of_appeal', models.CharField(default='Обратный звонок', max_length=55, verbose_name='Тип обращения')),
                ('time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратный звонок',
            },
        ),
    ]
