# Generated by Django 3.2.7 on 2022-06-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycallback',
            name='type_of_appeal',
            field=models.CharField(default='Обратный звонок', max_length=55, verbose_name='Тип обращения'),
        ),
    ]
