# Generated by Django 3.2.7 on 2022-06-08 09:12

import callback_form.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callback_form', '0002_alter_mycallback_type_of_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycallback',
            name='timestamp',
            field=callback_form.models.CustomDateTimeField(auto_now_add=True),
        ),
    ]
