# Generated by Django 3.2.7 on 2022-06-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20220608_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
