# Generated by Django 3.2.7 on 2022-06-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220608_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='line',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество линеек'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество товаров'),
        ),
    ]
