# Generated by Django 3.2.7 on 2022-06-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220608_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
    ]
