# Generated by Django 3.2.7 on 2022-06-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='line',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_quantity',
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.IntegerField(blank=True, null=True, verbose_name='Количество линеек')),
                ('product_quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество товаров')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderinfo', to='orders.orderitem')),
            ],
        ),
    ]
