# Generated by Django 3.2.7 on 2022-06-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_with_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
