# Generated by Django 3.2.7 on 2022-06-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_price_with_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.IntegerField(null=True, verbose_name='Скидки'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='line',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество линеек'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество товаров'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_cost',
            field=models.IntegerField(null=True, verbose_name='Итого к оплате'),
        ),
        migrations.DeleteModel(
            name='OrderInfo',
        ),
    ]
