# Generated by Django 3.2.7 on 2022-06-22 13:25

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Footer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(upload_to='Logo-img', verbose_name='Хедер лого')),
                ('footer_logo', models.ImageField(upload_to='Logo-img', verbose_name='Футер лого')),
                ('text', models.CharField(max_length=255)),
                ('header_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Хедер контакт')),
            ],
            options={
                'verbose_name': 'Футер1',
                'verbose_name_plural': 'Футер1',
            },
        ),
        migrations.CreateModel(
            name='Footer2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=155, verbose_name='Контакты')),
                ('mail', models.CharField(max_length=80, verbose_name='Почта')),
                ('instagram', models.CharField(max_length=100, verbose_name='Инстаграм')),
                ('telegram', models.CharField(max_length=80, verbose_name='Телеграм')),
                ('whatsapp', models.CharField(max_length=80, verbose_name='Ватсапп')),
            ],
            options={
                'verbose_name': 'Футер2',
                'verbose_name_plural': 'Футер2',
            },
        ),
        migrations.CreateModel(
            name='ImageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tab_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Помощь/Изображение',
                'verbose_name_plural': 'Помощь/Изображение',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tab_img', verbose_name='Фотография')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Публичная оферта',
                'verbose_name_plural': 'Публичная оферта',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('reply', models.TextField(verbose_name='Ответ')),
                ('Image_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='menu_tab.imagequestion', verbose_name='Помощь/Изображение')),
            ],
            options={
                'verbose_name': 'Вопрос/Ответ',
                'verbose_name_plural': 'Вопрос/Ответ',
            },
        ),
        migrations.CreateModel(
            name='Image_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='Картинки для О нас')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu_tab.about')),
            ],
        ),
    ]
