# Generated by Django 3.2.7 on 2022-06-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_tab', '0003_auto_20220605_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
