# Generated by Django 3.2.7 on 2022-06-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_tab', '0004_rename_text_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='body',
            new_name='reply',
        ),
    ]
