# Generated by Django 3.2.7 on 2022-06-05 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_tab', '0005_rename_body_reply_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tab_images')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='menu_tab.question')),
            ],
        ),
    ]
